function [A, b, lb, ub] = inequality_constraints(q_leg, q_leg_lb, q_leg_ub, dt)
    lb = [-Inf * ones(3,1);...
          -pi * ones(3,1);...
          (q_leg_lb - q_leg) / dt;... lb <= q_leg + dt*dq_leg <= ub
          -Inf * ones(16,1);...
          -Inf * ones(10,1);...
          -Inf * ones(12,1)];
    
    ub = [Inf * ones(3,1);...
          pi * ones(3,1);...
          (q_leg_ub - q_leg) / dt;...
          Inf * ones(16,1);...
          Inf * ones(10,1);...
          Inf * ones(12,1)];
      
    A = [zeros(12,6), zeros(12, 10), zeros(12, 16), zeros(12,10), zeros(12,12)];
    A(3, 45) = -1; % Vertical reaction forces, f must be >= 0; this is Aeq*x <= beq
    A(9, 51) = -1; %    so -f <= 0
    
    b = zeros(12,1); 
end